# Getting tests up and running on OSX:
#
# docker-machine create --driver virtualbox oauth
# docker-machine stop oauth
# VBoxManage modifyvm "oauth2" --natpf1 "tcp-port5432,tcp,,5432,,5432"
# docker-machine start oauth
# docker-compose build
# docker-compose up -d
# psql "dbname=oauth2_server user=postgres host=0.0.0.0 port=5432"
postgres:
  ports:
    - "5432:5432"
  build: roles/postgres
  restart: always
